export type Method='GET'|'POST'|'PATCH'|'DELETE';
export type Endpoint={method:Method;path:string;label:string;description:string};
export const endpoints:Endpoint[]=[{method:'GET',path:'/v1/customers/cus_8421',label:'Retrieve customer',description:'Returns one customer record.'},{method:'POST',path:'/v1/customers',label:'Create customer',description:'Creates a customer from a JSON payload.'},{method:'PATCH',path:'/v1/customers/cus_8421',label:'Update customer',description:'Updates selected customer fields.'},{method:'DELETE',path:'/v1/customers/cus_8421',label:'Delete customer',description:'Deletes a customer record.'},{method:'POST',path:'/v1/webhooks/test',label:'Test webhook',description:'Sends a simulated webhook delivery.'}];
export type Challenge={id:string;title:string;status:number;summary:string;evidence:string[];options:string[];answer:number;diagnosis:string;next:string;owner:string};
export const challenges:Challenge[]=[
{id:'CH-01',title:'Token rejected after key rotation',status:401,summary:'A customer says every API request started failing immediately after rotating credentials.',evidence:['Authorization: Bearer rd_live_old_••••','Response: invalid_token','New key was generated 12 minutes ago','No platform-wide auth alerts'],options:['API outage','Application still uses revoked token','Missing customer permission','Rate limit exhausted'],answer:1,diagnosis:'The integration is still sending the old revoked bearer token.',next:'Ask the customer to update the secret in the integration environment and retry. Never request the full secret in a support ticket.',owner:'Customer / Support guidance'},
{id:'CH-02',title:'Valid token, forbidden action',status:403,summary:'GET requests work, but the same integration cannot delete a customer.',evidence:['Bearer token validates successfully','GET /v1/customers → 200','DELETE /v1/customers/cus_8421 → 403','Token scope: customers:read'],options:['Token is malformed','Resource does not exist','Token lacks write/delete permission','RelayDesk is unavailable'],answer:2,diagnosis:'Authentication succeeds, but authorization scope is insufficient for the requested action.',next:'Verify required scopes and have an authorized admin issue credentials with the appropriate permission.',owner:'Customer configuration'},
{id:'CH-03',title:'Customer ID cannot be found',status:404,summary:'A customer can list records but a request for one copied ID returns not_found.',evidence:['GET /v1/customers → 200','GET /v1/customers/cus_2481 → 404','Requested ID: cus_2481','Visible record ID: cus_8421'],options:['Wrong resource identifier','Expired authentication','Invalid JSON','Rate limiting'],answer:0,diagnosis:'The request targets an identifier that does not match the existing resource.',next:'Confirm the resource ID from the successful list response and retry with the correct path.',owner:'Customer / Support guidance'},
{id:'CH-04',title:'Payload passes JSON parsing but fails validation',status:422,summary:'A create request contains valid JSON but RelayDesk refuses the field values.',evidence:['Content-Type: application/json','JSON parses successfully','email: "not-an-email"','Response field: email'],options:['Server crashed','Semantic validation failed','Authorization scope missing','HTTP method unsupported'],answer:1,diagnosis:'The syntax is valid JSON, but the supplied email does not satisfy the API field requirements.',next:'Correct the field value according to the schema and resend the request.',owner:'Customer payload'},
{id:'CH-05',title:'Burst traffic starts failing',status:429,summary:'An integration works normally, then a batch job produces intermittent failures.',evidence:['First requests → 200','x-ratelimit-limit: 100','x-ratelimit-remaining: 0','retry-after: 30'],options:['Database corruption','Webhook signature error','Rate limit exceeded','Invalid endpoint'],answer:2,diagnosis:'The client exhausted its request quota during the traffic burst.',next:'Respect Retry-After, implement backoff and reduce unnecessary request bursts.',owner:'Customer integration / Support guidance'},
{id:'CH-06',title:'Same request fails across independent accounts',status:500,summary:'Multiple customers report the same endpoint returning an internal error.',evidence:['Three independent accounts affected','Requests previously worked unchanged','Authentication validates','Platform error IDs correlate in the same time window'],options:['Each customer independently misconfigured JSON','Likely shared platform failure','All tokens expired together','Expected rate-limit behavior'],answer:1,diagnosis:'Cross-account correlated 500s with previously healthy requests indicate a likely platform-side failure.',next:'Preserve request/error IDs, timestamps and impact; check service health and escalate to Engineering/incident response.',owner:'Engineering / Incident path'}];
